### ISSUE TITLE
Implement sps_api_plugin skeleton

### ISSUE THREAD

**Issue by vogel76** [blocktradesdevs/steem#2]
- [x] Define plugin structure
- [x] Design RPC API interface to query for proposal data

**Comment by vogel76** [comment]
Basic RPC API documentation is located here:
https://github.com/blocktradesdevs/steem/wiki/SPS-API-Plugin

**Comment by inertia186** [comment]
Shouldn’t these be broadcast operations so they can be cryptography signed?

**Comment by vogel76** [comment]
Indeed all modifications shall be part of regular transaction schedule. Thanks for your opinion.

**Comment by inertia186** [comment]
Nice.

I would also like to suggest that RPC method arguments follow the previously established standard, for example:

https://developers.steem.io/apidefinitions/#database_api.find_escrows-curl-examples

This means that instead of `data`, as in:

```bash
curl --data-binary '{"jsonrpc":"2.0","id":"2","method":"sps_api.find_proposal", "data" : {"id" : 1234}}' http://127.0.0.1:8751
```

... `data` becomes `params`, for example:

```bash
curl --data-binary '{"jsonrpc":"2.0","id":"2","method":"sps_api.find_proposal", "params" : {"id" : 1234}}' http://127.0.0.1:8751
```

Using the `params` key is a better fit for our existing tools.

**Comment by dkedzierski** [comment]
Thanks for pointing that out. Fixed.
