### ISSUE TITLE
SPS Objects contain non-unique indices

### ISSUE THREAD

**Issue by mvandeberg** [blocktradesdevs/steem#78]
https://github.com/blocktradesdevs/steem/blob/e3ccfd6d9203cfc69a4386ea90afb8ce416a7805/libraries/chain/include/steem/chain/sps_objects.hpp#L108-L118

The non-unque indices should be made unique by making the unique composite keys with the object id appended. This is a matter of best practice because ordering of non-unique indices becomes tricky and potentially non-deterministic when undo states are undone and re-applied.

**Comment by dnotestein** [comment]
_by_total_votes_ should be unique to avoid potential forking in the face of different sorting algorithm implentations. But we disagree with the premise that the others should be, as it's not at all clear how undo will cause problems. But it's a pain to prove otherwise, and I don't want to spend the time on it. So we'll continue with the probably unnecessary overhead (it's all over the place in the code anyways).
