### ISSUE TITLE
create_proposal_evaluator feedback

### ISSUE THREAD

**Issue by mvandeberg** [blocktradesdevs/steem#79]
- [ ] `const auto& treasury_account =_db.get_account( STEEM_TREASURY_ACCOUNT );` not needed because treasury account already exists.

- [ ] `_db.get_account( o.receiver );` should be `find_account` and an assertion to provide reasonable error message on failure.

- [ ] Should start date be greater than head block time?

- [ ] Should end date be greater than head block time?

**Comment by vogel76** [comment]
In PR https://github.com/blocktradesdevs/steem/pull/92

-   added additional check against end_date,
-   enhanced error message when receiver account does not exist.
-   treasury_account must be left - its balance is adjusted at the end of evaluation.
-   there is no start_date check since otherwise it could be troublesome (start_date shall include some potential delay in transaction processing i.e. one block).
