### ISSUE TITLE
SPS: I can vote for removed proposal

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [blocktradesdevs/steem#83]
For which I can't see any valid use case scenario.

**Comment by bwsdeveloper** [comment]
Vote operation can take multiple proposal IDs. We decided just to ignore nonexisting ones, to accept other valids IDs passed to operation. If we will throw at any invalid id, others will be ignored and whole operation aborted - does it is expected behavior ?

**Comment by emre** [comment]
I'd prefer getting an error on that - even though the payload includes valid proposal IDs.

**Comment by dnotestein** [comment]
I think it's better to ignore invalid ids. Many interfaces will probably support and even encourage voting on multiple proposals at once and a user shouldn't have to vote again just because one of the proposals has been removed. The user has no proactive step to take if the proposal has been removed: it's gone and he can't vote for or against it anymore.

The only case I could see for this would be if some of the proposals were linked in some manner, so that user only wants to change the vote on one if he can change the vote on the other one also, but I think this isn't one of the likely real world cases.

**Comment by Gandalf-the-Grey** [comment]
@bwsdeveloper and @dnotestein might be right here, so while there's no point for voting for already removed proposal, ignoring such vote instead of failing whole update (for a larger set) just because one is already gone seems to be OK.
